### ISSUE TITLE
Logger is broken

### ISSUE THREAD

**Issue by dyerw** [prescottprue/authrocket#2]
in config.js:

```
 get logLevel () {
    if (level) {
      return level
    }
    return defaultConfig.envs[envName].logLevel
  }
```

however this is defaultConfig:

```
let defaultConfig = {
  accountId: process.env.AUTHROCKET_ACCOUNT_ID,
  apiKey: process.env.AUTHROCKET_API_KEY,
  realmId: process.env.AUTHROCKET_REALM_ID,
  jwtSecret: process.env.AUTHROCKET_JWT_SECRET,
  apiUrl: process.env.AUTHROCKET_API_URL || 'https://api-e1.authrocket.com/v1/',
  jsUrl: process.env.AUTHROCKET_JS_URL
}
```

which has no "envs" key so i get this error:

```
bundle.js:36741 uncaught at loginSaga 
 at tryToLogin 
 TypeError: Cannot read property 'prod' of undefined
    at Config.get (http://localhost:8080/bundle.js:60224:34)
    at buildMessageArgs (http://localhost:8080/bundle.js:63639:25)
    at Object.log (http://localhost:8080/bundle.js:63591:19)
    at AuthRocket.login (http://localhost:8080/bundle.js:58907:26)
    at authenticateUser (http://localhost:8080/bundle.js:66152:24)
    at runCallEffect (http://localhost:8080/bundle.js:37198:20)
    at runEffect (http://localhost:8080/bundle.js:37127:400)
    at next (http://localhost:8080/bundle.js:37011:10)
    at currCb (http://localhost:8080/bundle.js:37081:8)
    at runSelectEffect (http://localhost:8080/bundle.js:37403:8)
```

**Comment by prescottprue** [comment]
Looking into this now. Thanks for pointing it out.
